[versions]
android-gradle-plugin = "8.5.2"
android-junit5 = "1.12.0.0"
androidx-activity-ktx = "1.10.1"
androidx-appcompat = "1.7.0"
androidx-constraintlayout = "2.2.1"
androidx-core-ktx = "1.15.0"
androidx-espresso-core = "3.6.1"
androidx-test-ext-junit = "1.2.1"
androidx-test-runner = "1.6.2"
assertj-core = "3.27.3"
core-testing = "2.2.0"
glide = "4.16.0"
kotlinx-serialization-json = "1.8.1"
retrofit-serialization-converter = "0.8.0"
google-material = "1.12.0"
gson = "2.11.0"
junit-jupiter = "5.12.0"
kotest-runner-junit5 = "5.9.1"
kotlin = "2.1.0"
ktlint = "12.1.0"
mannodermaus-junit5 = "1.7.0"
mockk-android = "1.14.0"
mockwebserver = "4.12.0"
okhttp = "4.12.0"
retrofit = "3.0.0"
room-runtime = "2.7.1"
room-compiler = "2.7.1"
shimmer = "0.5.0"

[libraries]
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidx-activity-ktx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "core-testing" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room-compiler" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room-runtime" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test-runner" }
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertj-core" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
google-glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "mockwebserver" }
retrofit-kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit-serialization-converter" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "google-material" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit-jupiter" }
kotest-runner-junit5 = { group = "io.kotest", name = "kotest-runner-junit5", version.ref = "kotest-runner-junit5" }
mannodermaus-junit5-core = { group = "de.mannodermaus.junit5", name = "android-test-core", version.ref = "mannodermaus-junit5" }
mannodermaus-junit5-runner = { group = "de.mannodermaus.junit5", name = "android-test-runner", version.ref = "mannodermaus-junit5" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk-android" }
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "mockwebserver" }
okhttp3-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-junit5 = { id = "de.mannodermaus.android-junit5", version.ref = "android-junit5" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
